apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-sub
  namespace: openshift-operators 
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  channel: stable
  name: elasticsearch-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 

