apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaegar-sub
  namespace: openshift-operators 
  annotations:
    argocd.argoproj.io/sync-wave: "22"
spec:
  channel: stable
  name: jaeger-product
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 

