apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: smesh-sub
  namespace: openshift-operators 
  annotations:
    argocd.argoproj.io/sync-wave: "24"

spec:
  channel: stable
  name: servicemeshoperator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 

